<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:ricevutans="http://invioerogatoricevuta.xsd.dem.sanita.finanze.it" xmlns:richiestans="http://invioerogatorichiesta.xsd.dem.sanita.finanze.it" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://invioerogato.wsdl.dem.sanita.finanze.it" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://invioerogato.wsdl.dem.sanita.finanze.it">
	<wsdl:types>
		<xsd:schema elementFormDefault="qualified">
			<xsd:import namespace="http://invioerogatorichiesta.xsd.dem.sanita.finanze.it" schemaLocation="InvioErogatoRichiesta.xsd"/>
		</xsd:schema>
		<xsd:schema elementFormDefault="qualified">
			<xsd:import namespace="http://invioerogatoricevuta.xsd.dem.sanita.finanze.it" schemaLocation="InvioErogatoRicevuta.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="ricevuta">
		<wsdl:part name="InvioErogatoRicevuta" element="ricevutans:InvioErogatoRicevuta"/>
	</wsdl:message>
	<wsdl:message name="richiesta">
		<wsdl:part name="InvioErogatoRichiesta" element="richiestans:InvioErogatoRichiesta"/>
	</wsdl:message>
	<wsdl:portType name="invioErogatoPT">
		<wsdl:operation name="invioErogato">
			<wsdl:input message="tns:richiesta"/>
			<wsdl:output message="tns:ricevuta"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="invioErogatoBinding" type="tns:invioErogatoPT">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="invioErogato">
			<soap:operation soapAction="http://invioerogato.wsdl.dem.sanita.finanze.it/InvioErogato"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="demInvioErogato">
		<wsdl:port name="demInvioErogato" binding="tns:invioErogatoBinding">
			<soap:address location="http://localhost:9080/DemRicettaErogatoServicesWeb/services/demInvioErogato"/>
		</wsdl:port>
	</wsdl:service>
	<wsdl:documentation>Versione 1.2</wsdl:documentation>
</wsdl:definitions>
